name: benchgen
version: git
summary: Generates output from an XCCDF file.
description: |
  Generates complex output from an XCCDF file. Used to generate initial project files for automation tools in various formats.
license: MIT

base: core20
grade: stable
confinement: strict
compression: lzo

apps:
  benchgen:
    command: bin/benchgen
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network  

parts:
  benchgen:
    source: https://github.com/ansible-lockdown/Benchmark-Generator
    source-type: git
    plugin: python
    
    build-packages:
      - pipenv
      
    stage-packages:
      - pipenv
      - python3-jinja2
