name: benchgen
adopt-info: benchgen
summary:
description: |

license: MIT

base: core20
grade: stable
confinement: strict
compression: lzo

apps:
  benchgen:
    command: bin/benchgen
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network  

parts:
  benchgen:
    source: https://github.com/ansible-lockdown/Benchmark-Generator
    source-type: git
    plugin: python
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
    
    build-packages:
      - pipenv
      
    stage-packages:
      - pipenv
